from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
SPLITS = DATA / "splits"
SFT_DIR = DATA / "sft"
GEMINI_SFT_DIR = SFT_DIR / "gemini"
SPLIT_META = SPLITS / "split.json"
TRAIN_IDS = SPLITS / "train.json"
EVAL_IDS = SPLITS / "eval.json"
SFT_JSONL = SFT_DIR / "spreadsheet_sft.jsonl"
SFT_MANIFEST = SFT_DIR / "manifest.jsonl"
SFT_SMALL_JSONL = SFT_DIR / "spreadsheet_sft_small.jsonl"
GEMINI_SFT_JSONL = GEMINI_SFT_DIR / "spreadsheet_sft.jsonl"
GEMINI_SFT_MANIFEST = GEMINI_SFT_DIR / "manifest.jsonl"
MERGED_SFT_JSONL = SFT_DIR / "spreadsheet_sft_merged.jsonl"
MERGED_SFT_MANIFEST = SFT_DIR / "manifest_merged.jsonl"
DATA_912 = DATA / "all_data_912_v0.1"
VERIFIED_400 = DATA / "spreadsheetbench_verified_400"
SFT_512_CASE1_JSONL = SFT_DIR / "sft_512_case1.jsonl"
SFT_512_CASE1_MANIFEST = SFT_DIR / "manifest_512_case1.jsonl"
SFT_512_FULL_JSONL = SFT_DIR / "sft_512_full.jsonl"
SFT_512_FULL_MANIFEST = SFT_DIR / "manifest_512_full.jsonl"
RL_DIR = DATA / "rl"
RL_TRAIN_JSONL = RL_DIR / "rl_train.jsonl"
RL_DEV_JSONL = RL_DIR / "rl_dev.jsonl"
RL_SUMMARY = RL_DIR / "summary.json"
TRACE_SFT_JSONL = SFT_DIR / "sft_train_traces.jsonl"
TRACE_SFT_MANIFEST = SFT_DIR / "manifest_train_traces.jsonl"
RESIDUAL_SFT_JSONL = SFT_DIR / "sft_residual.jsonl"
RESIDUAL_SFT_MANIFEST = SFT_DIR / "manifest_residual.jsonl"
SMALL_CELL_LIMIT = 200
RL_DEV_BASE_FRACTION = 0.1
RL_DEV_BASE_MIN = 16
RL_DEV_BASE_MAX = 32
SHIPPED_SFT_WEIGHTS = "tinker://6fddcac0-b2a6-545a-b7e4-b3886d94d9d6:train:0/weights/final"
EVAL_CELL = 56
EVAL_SHEET = 24
SPLIT_SEED = 42
